### ISSUE TITLE
aarch64 and ppc64le builds not working anymore

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy-feedstock#187]
Looks like https://github.com/conda-forge/conda-smithy-feedstock/pull/184 added shellcheck which is not built for these platforms. I'm not sure why that requirement is there.

cc @beckermr

**Comment by beckermr** [comment]
Well I broke it. :/

**Comment by beckermr** [comment]
shellcheck is in the upstream recipe: https://github.com/conda-forge/conda-smithy/commit/c8d6c01fadd68f3a12b68d8710da082f0ee47643

**Comment by beckermr** [comment]
so I guess we need to remove it there?

**Comment by isuruf** [comment]
It's for a feature that we don't use in conda-forge and that commit has been there since 3.6.3, but we didn't add it.

**Comment by beckermr** [comment]
ah ok
