### ISSUE TITLE
pin conda-build-all requirement

### ISSUE THREAD

**Issue by jakevdp** [conda-forge/conda-smithy-feedstock#45]
I recently updated conda-smithy and had a failure because I was on conda-build-all v0.11 (see https://github.com/conda-forge/vega-feedstock/pull/12#issuecomment-253573312)

This requirement should probably be pinned to prevent this in the future.

**Comment by jakirkham** [comment]
Copying myself from that PR as I hadn't seen this yet.

The situation is more that to use `conda-build` version `2.0.x` one needs `conda-build-all` version `1.0.0` and the `conda-smithy` version `1.2.0` or greater. Basically, this error wouldn't have occurred with `conda-build` version `1.21.x` and the old `conda-build-all`. Not sure the right way to specify that ATM as I don't think we have conditional versioning of this sort.

**Comment by jakirkham** [comment]
Consolidating into issue ( https://github.com/conda-forge/conda-smithy/issues/375 ).
